### ISSUE TITLE
Error installing mdy

### ISSUE THREAD

**Issue by djadmin** [IonicaBizau/mdy#3]
Please have a look at the follwoing stack-trace after trying 
`$ npm install -g mdy`

```
/usr/local/lib/node_modules/mdy/node_modules/image-to-ascii/node_modules/imgpx/node_modules/lwipify/node_modules/lwip2/scripts/install.js:5
const gmInstalled = require("gm-installed")
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "mdy"
npm ERR! node v0.12.8
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE

npm ERR! lwip2@1.0.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip2@1.0.3 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the lwip2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lwip2
npm ERR! There is likely additional logging output above.
```

Let me know if you need more information.

**Comment by IonicaBizau** [comment]
Can you please tell me the node.js version you're running? `node --version`?

**Comment by djadmin** [comment]
v0.12.8
I know it's pretty old. Would it be possible to run on this?

**Comment by IonicaBizau** [comment]
Actually, I do babelify the things before publishing on npm. I will take a look in the morning. 😴

**Comment by greg-js** [comment]
I can confirm this problem on Node v0.12.

On Node v4.4.5 and v6.2.1 I am getting a different installation error:

Node v4.4.5:
```
$ npm install -g mdy
 
> deasync@0.1.7 install /home/greg/.nvm/versions/node/v4.4.5/lib/node_modules/mdy/node_modules/deasync
> node ./build.js

`linux-x64-node-4` exists; testing
Binary is fine; exiting
 
> lwip2@1.0.3 install /home/greg/.nvm/versions/node/v4.4.5/lib/node_modules/mdy/node_modules/image-to-ascii/node_modules/image-parser/node_modules/lwipify/node_modules/lwip2
> node scripts/install.js

Detected GraphicsMagick. Using it. :)

> lwip2@1.0.3 install /home/greg/.nvm/versions/node/v4.4.5/lib/node_modules/mdy/node_modules/image-to-ascii/node_modules/imgpx/node_modules/lwipify/node_modules/lwip2
> node scripts/install.js

Detected GraphicsMagick. Using it. :)
npm ERR! Linux 4.6.3-1-ARCH
npm ERR! argv "/home/greg/.nvm/versions/node/v4.4.5/bin/node" "/home/greg/.nvm/versions/node/v4.4.5/bin/npm" "install" "-g" "mdy"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path /home/greg/.nvm/versions/node/v4.4.5/lib/node_modules/mdy/mdy
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/greg/.nvm/versions/node/v4.4.5/lib/node_modules/mdy/mdy'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
```

Node v6.2.1:
```
$ npm install -g mdy
npm ERR! Linux 4.6.3-1-ARCH
npm ERR! argv "/home/greg/.nvm/versions/node/v6.2.1/bin/node" "/home/greg/.nvm/versions/node/v6.2.1/bin/npm" "install" "-g" "mdy"
npm ERR! node v6.2.1
npm ERR! npm  v3.10.2
npm ERR! path /home/greg/.nvm/versions/node/v6.2.1/lib/node_modules/mdy/mdy
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/greg/.nvm/versions/node/v6.2.1/lib/node_modules/mdy/mdy'
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/greg/.nvm/versions/node/v6.2.1/lib/node_modules/mdy/mdy'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
```

I thought it might be because of me using `nvm`, but I tested on a different machine that doesn't have `nvm` and I got the same error.

Is it possible the `./mdy` script was somehow never pushed to the npm package? I ask because if I `git clone` the repo and `npm link`, it works perfectly fine, but with a local or global `npm install`, it fails to find `./mdy`

**Comment by IonicaBizau** [comment]
@djadmin @greg-js Can you please do it again? It should be fixed now, in the latest release.

**Comment by greg-js** [comment]
Works great now! Awesome package :D

**Comment by IonicaBizau** [comment]
The issue is that I'm automatically whitelisting the files to publish on npm and I did the mistake to not put the `mdy` executable in the `bin` folder. Then the `mdy` file was ignored and wasn't uploaded on npm at all. 💥 

Have fun! I often use it when I need to preview Markdown. 😁 

💡 Tip: `mdy README.md | less` works great. 😁

**Comment by djadmin** [comment]
Ah! It's still not working for me, it seems.
>/mdy/node_modules/image-to-ascii/node_modules/image-parser/node_modules/lwipify/node_modules/lwip2/scripts/install.js:5
const gmInstalled = require("gm-installed")
^^^^^
SyntaxError: Use of const in strict mode.

Am I missing something here?

**Comment by IonicaBizau** [comment]
Try to `npm i` again. `lwip2` is supposed to come with the latest changes from npm. Also, check what is the version in `/mdy/node_modules/image-to-ascii/node_modules/image-parser/node_modules/lwipify/node_modules/lwip2/package.json`.

**Comment by IonicaBizau** [comment]
Also, make sure you run a recent enough Node.js version. The code on npm is transpiled, but it seems like the scripts are not.

I'm rebuilding the packages.
